MVC/Models/Structure.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MVC.Models
{
    public class Structure
    {
        [Key]
        [Required]
        public Guid Id { get; set; }

        public string Name { get; set; }

        public virtual ICollection<Project> Project { get; set; }
    }
}

MVC/ViewModels/StructureViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using MVC.Models;

namespace MVC.ViewModels
{
    public class StructureViewModel
    {
        public Guid Id { get; set; }

        public string Name { get; set; }
    }

    public class StructureListViewModel
    {
        public IEnumerable<Structure> StructureList { get; set; }
    }
}

MVC/Controllers/StructureController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC.Models;
using MVC.Models.Interface;
using MVC.Models.Repository;
using MVC.ViewModels;

namespace MVC.Controllers
{
    public class StructureController : Controller
    {
        private readonly IRepository<Structure> structureRepository;

        public StructureController()
        {
            this.structureRepository = new GenericRepository<Structure>();
        }

        // GET: Structure
        public ActionResult Index()
        {
            var structures = structureRepository.GetAll().ToList();
            var viewModel = new StructureListViewModel();
            viewModel.StructureList = structures;

            return View(viewModel);
        }

        public ActionResult Create()
        {
            var viewModel = new StructureViewModel();

            return View(viewModel);
        }

        public ActionResult Edit(Guid id)
        {
            var viewModel = new StructureViewModel();
            var model = structureRepository.GetById(x => x.Id == id);
            viewModel.Id = id;
            viewModel.Name = model.Name;

            return View("Create", viewModel);
        }

        [HttpPost]
        public ActionResult Save(StructureViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                if (viewModel.Id == Guid.Empty)
                {
                    var model = new Structure();
                    model.Id = Guid.NewGuid();
                    model.Name = viewModel.Name;
                    structureRepository.Create(model);
                }
                else
                {
                    var model = structureRepository.GetById(x => x.Id == viewModel.Id);
                    model.Name = viewModel.Name;
                    structureRepository.Update(model);
                }
                return RedirectToAction("Index");
            }
            return View("Create", viewModel);
        }

        public ActionResult Delete(Guid id)
        {
            var model = structureRepository.GetById(x => x.Id == id);
            structureRepository.Delete(model);

            return RedirectToAction("Index");
        }
    }
}

MVC/Views/Structure/Create.cshtml
@model MVC.ViewModels.StructureViewModel

@if (Model.Id == Guid.Empty)
{
    {
        ViewBag.Title = "新增";
    }
    <h2>新增</h2>

    <h4>新增結構。</h4>
}
else
{
    {
        ViewBag.Title = "編輯";
    }
    <h2>編輯</h2>

    <h4>編輯結構。</h4>
}

<hr />
@using (Html.BeginForm("Save", "Structure", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.HiddenFor(x => x.Id)

    <div class="form-group">
        @Html.Label("結構名稱", new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="送出" />
        </div>
    </div>
}

MVC/Views/Structure/Index.cshtml
@model MVC.ViewModels.StructureListViewModel

@{
    ViewBag.Title = "顯示";
}
<h2>@ViewBag.Title.</h2>

<h4>顯示結構。</h4>
@Html.ActionLink("新增", "Create", "Structure", new { @class = "btn btn-primary" })
<hr />
<table class="table table-bordered table-striped">
    <thead>
        <tr class="alert-info">
            <th>結構名稱</th>
            <th>動作</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.StructureList)
        {
            <tr>
                <td>@item.Name</td>
                <td>
                    @Html.ActionLink("編輯", "Edit", new { id = item.Id }, new { @class = "btn btn-info" })
                    @Html.ActionLink("刪除", "Delete", new { id = item.Id }, new { @class = "btn btn-danger" })
                </td>
            </tr>
        }
    </tbody>
</table>